print ('    *\n   * *\n  *   *\n *     *\n*       *\n***   ***')
print('  *   *\n  *   *\n  *****')
print('Ahora una flecha normal')
print('      *')
print('     * *')
print('    *   *')
print('   *     *')
print('  ***   ***')
print('    *   *')
print('    *   *')
print('    *****')
print('Ahora Doble')
print('        *'      *2)
print('       * *'     *2)
print('      *   *'    *2)
print('     *     *'   *2)
print('    ***   ***'  *2)
print('      *   *'    *2)
print('      *   *'    *2)
print('      *****'    *2)
